# Generated by Django 5.2.4 on 2025-07-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('definitions', models.JSONField()),
                ('synonyms', models.JSONField(blank=True, null=True)),
                ('antonyms', models.JSONField(blank=True, null=True)),
                ('examples_by_style', models.JSONField(blank=True, null=True)),
                ('story_mnemonic', models.TextField(blank=True, null=True)),
                ('etymology', models.TextField(blank=True, null=True)),
                ('related_words', models.JSONField(blank=True, null=True)),
                ('mastery', models.IntegerField(default=0)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('user_data', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
