# Generated by Django 5.2.4 on 2025-07-20 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='user_data',
        ),
        migrations.AddField(
            model_name='word',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='last_practiced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='time_spent_quiz',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='word',
            name='time_spent_read',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='word',
            name='times_asked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='word',
            name='times_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
