# Generated by Django 5.2.4 on 2025-07-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0002_remove_word_user_data_word_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='definitions',
        ),
        migrations.RemoveField(
            model_name='word',
            name='examples_by_style',
        ),
        migrations.RemoveField(
            model_name='word',
            name='related_words',
        ),
        migrations.AddField(
            model_name='word',
            name='category',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='word',
            name='connotation',
            field=models.CharField(default='neutral', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='difficulty_level',
            field=models.CharField(default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='examples',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='word',
            name='external_links',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='word',
            name='meaning',
            field=models.TextField(default=str),
        ),
        migrations.AddField(
            model_name='word',
            name='pronunciation',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='word',
            name='spaced_repetition',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='word',
            name='user_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='word',
            name='word_breakdown',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='word',
            name='word_grouping',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='word',
            name='antonyms',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='word',
            name='etymology',
            field=models.TextField(default=str),
        ),
        migrations.AlterField(
            model_name='word',
            name='last_practiced',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='word',
            name='source',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='word',
            name='story_mnemonic',
            field=models.TextField(default=str),
        ),
        migrations.AlterField(
            model_name='word',
            name='synonyms',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='word',
            name='tags',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(default='N/A', max_length=100, unique=True),
        ),
    ]
