# Generated by Django 5.2.4 on 2025-07-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0003_remove_word_definitions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='etymology',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='word',
            name='meaning',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='word',
            name='pronunciation',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='word',
            name='source',
            field=models.CharField(blank=True, default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='word',
            name='story_mnemonic',
            field=models.TextField(blank=True, default=''),
        ),
    ]
