# Generated by Django 5.2.4 on 2025-07-26 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0004_alter_word_etymology_alter_word_meaning_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MathQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.CharField(max_length=100)),
                ('solution_steps', models.TextField()),
                ('topic', models.CharField(blank=True, default='general', max_length=100)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=20)),
                ('number', models.IntegerField(default=0)),
                ('mastery', models.IntegerField(default=0)),
                ('times_asked', models.IntegerField(default=0)),
                ('times_correct', models.IntegerField(default=0)),
                ('time_spent_quiz', models.IntegerField(default=0)),
                ('time_spent_read', models.IntegerField(default=0)),
                ('last_practiced', models.DateTimeField(blank=True, null=True)),
                ('spaced_repetition', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
