# Generated by Django 5.2.4 on 2025-07-26 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0005_mathquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='connotation',
            field=models.CharField(default='neutral', max_length=100),
        ),
    ]
