# Generated by Django 5.2.4 on 2025-08-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0007_reviewsession_userwordprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwordprogress',
            name='repetitions',
            field=models.IntegerField(default=0),
        ),
    ]
