# Generated by Django 5.2.4 on 2025-08-22 23:04

import django.db.models.deletion
import vocab.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0008_userwordprogress_repetitions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userwordprogress',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='reviewsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reviewsession',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_sessions', to='vocab.word'),
        ),
        migrations.AlterField(
            model_name='userwordprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userwordprogress',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='vocab.word'),
        ),
        migrations.AlterField(
            model_name='word',
            name='examples',
            field=models.JSONField(default=vocab.models.default_examples),
        ),
        migrations.AlterField(
            model_name='word',
            name='spaced_repetition',
            field=models.JSONField(default=vocab.models.default_spaced_repetition),
        ),
        migrations.AlterField(
            model_name='word',
            name='user_data',
            field=models.JSONField(default=vocab.models.default_user_data),
        ),
        migrations.AlterField(
            model_name='word',
            name='word_breakdown',
            field=models.JSONField(default=vocab.models.default_word_breakdown),
        ),
        migrations.AddConstraint(
            model_name='userwordprogress',
            constraint=models.UniqueConstraint(fields=('user', 'word'), name='uniq_user_word_progress'),
        ),
    ]
