# Generated by Django 5.2.4 on 2025-08-23 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0009_alter_userwordprogress_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwordprogress',
            name='next_review',
        ),
    ]
