# Generated by Django 5.2.4 on 2025-08-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0010_remove_userwordprogress_next_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='group_number',
            field=models.IntegerField(db_index=True, default=1),
        ),
    ]
