# Generated by Django 5.2.4 on 2025-08-29 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0012_quizsession_quizattempt_userstreak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathquestion',
            name='mastery',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userwordprogress',
            name='mastery',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='word',
            name='mastery',
            field=models.IntegerField(default=1),
        ),
    ]
