# Generated by Django 5.2.4 on 2025-08-29 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0013_alter_mathquestion_mastery_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.IntegerField()),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('mastery_threshold', models.IntegerField(default=3)),
                ('words_total', models.IntegerField(default=0)),
                ('words_started', models.IntegerField(default=0)),
                ('words_mastered', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['group_number', 'created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='userwordprogress',
            name='uniq_user_word_progress',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='attempts_until_correct',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='time_taken',
        ),
        migrations.RemoveField(
            model_name='quizsession',
            name='max_streak',
        ),
        migrations.RemoveField(
            model_name='quizsession',
            name='streak_count',
        ),
        migrations.RemoveField(
            model_name='quizsession',
            name='time_limit',
        ),
        migrations.RemoveField(
            model_name='quizsession',
            name='time_spent',
        ),
        migrations.AlterUniqueTogether(
            name='userwordprogress',
            unique_together={('user', 'word')},
        ),
        migrations.RemoveField(
            model_name='word',
            name='connotation',
        ),
        migrations.RemoveField(
            model_name='word',
            name='last_practiced',
        ),
        migrations.RemoveField(
            model_name='word',
            name='mastery',
        ),
        migrations.RemoveField(
            model_name='word',
            name='spaced_repetition',
        ),
        migrations.RemoveField(
            model_name='word',
            name='time_spent_quiz',
        ),
        migrations.RemoveField(
            model_name='word',
            name='time_spent_read',
        ),
        migrations.RemoveField(
            model_name='word',
            name='times_asked',
        ),
        migrations.RemoveField(
            model_name='word',
            name='times_correct',
        ),
        migrations.RemoveField(
            model_name='word',
            name='user_data',
        ),
        migrations.RemoveField(
            model_name='word',
            name='word_grouping',
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='consecutive_correct_after',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='consecutive_correct_before',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='is_retry_attempt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='mastery_after',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='mastery_before',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='time_taken_ms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='group_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='group_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='retry_queue',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='retry_requirements',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='unique_words_practiced',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='word_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='words_mastered_this_session',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userwordprogress',
            name='consecutive_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userwordprogress',
            name='first_seen',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userwordprogress',
            name='interval_days',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userwordprogress',
            name='is_learning',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userwordprogress',
            name='marked_for_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userwordprogress',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='word',
            name='total_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='word',
            name='total_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='options_presented',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='question_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='quiz_type',
            field=models.CharField(choices=[('adaptive_group', 'Adaptive Group Quiz'), ('spaced_review', 'Spaced Repetition Review'), ('low_mastery', 'Low Mastery Drill'), ('cycle_mode', 'Cycle Mode Quiz'), ('due_review', 'Due Review Quiz')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userwordprogress',
            name='last_practiced',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userwordprogress',
            name='mastery',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='word',
            name='category',
            field=models.CharField(default='vocabulary', max_length=50),
        ),
        migrations.AlterField(
            model_name='word',
            name='etymology',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='group_number',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='meaning',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='word',
            name='pronunciation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='word',
            name='story_mnemonic',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['session', 'timestamp'], name='vocab_quiza_session_a308ab_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['word', 'is_correct'], name='vocab_quiza_word_id_850ab0_idx'),
        ),
        migrations.AddIndex(
            model_name='quizsession',
            index=models.Index(fields=['user', 'is_active'], name='vocab_quizs_user_id_82db5f_idx'),
        ),
        migrations.AddIndex(
            model_name='quizsession',
            index=models.Index(fields=['user', 'quiz_type'], name='vocab_quizs_user_id_6922da_idx'),
        ),
        migrations.AddIndex(
            model_name='userwordprogress',
            index=models.Index(fields=['user', 'mastery'], name='vocab_userw_user_id_367667_idx'),
        ),
        migrations.AddIndex(
            model_name='userwordprogress',
            index=models.Index(fields=['user', 'due_date'], name='vocab_userw_user_id_d4e80d_idx'),
        ),
        migrations.AddIndex(
            model_name='userwordprogress',
            index=models.Index(fields=['user', 'is_learning'], name='vocab_userw_user_id_384bae_idx'),
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['group_number'], name='vocab_word_group_n_5e1722_idx'),
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['created_at'], name='vocab_word_created_9c5083_idx'),
        ),
        migrations.AddField(
            model_name='groupprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='userwordprogress',
            name='ease_factor',
        ),
        migrations.RemoveField(
            model_name='userwordprogress',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='userwordprogress',
            name='repetitions',
        ),
        migrations.AddIndex(
            model_name='groupprogress',
            index=models.Index(fields=['user', 'is_completed'], name='vocab_group_user_id_0fe4b9_idx'),
        ),
        migrations.AddIndex(
            model_name='groupprogress',
            index=models.Index(fields=['user', 'group_number'], name='vocab_group_user_id_408fec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupprogress',
            unique_together={('user', 'group_number')},
        ),
    ]
