# Generated by Django 5.2.4 on 2025-08-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0014_groupprogress_alter_word_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='word_grouping',
            field=models.JSONField(default=list),
        ),
    ]
